title: Aalok's Blog
author: Aalok Singh
email: aalok_2@live.com
description: > # this means to ignore newlines until "twitter_username:"
  All content written by me is by default released freely under the [WTFPL](www.wtfpl.net).

# social links
twitter_username: devaalok
github_username:  aalok05


show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
